import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'te';

const teluguTranslations: Record<string, string> = {
  Language: 'భాష',
  Account: 'ఖాతా',
  'Sign in to access your farm diagnostics & history': 'మీ వ్యవసాయ నిర్ధారణలు మరియు చరిత్రను చూడటానికి సైన్ ఇన్ చేయండి',
  'Join the botanical health & pathology network': 'మొక్కల ఆరోగ్యం మరియు వ్యాధి విశ్లేషణ నెట్‌వర్క్‌లో చేరండి',
  'Use Demo Pass': 'డెమో పాస్‌వర్డ్ ఉపయోగించండి',
  'Quick Evaluation Demo Accounts:': 'త్వరిత పరీక్ష డెమో ఖాతాలు:',
  'Farm / Greenhouse / Institution Name': 'వ్యవసాయ క్షేత్రం / గ్రీన్‌హౌస్ / సంస్థ పేరు',
  'Select Your Role': 'మీ పాత్రను ఎంచుకోండి',
  'Agronomist / Scientist': 'వ్యవసాయ నిపుణుడు / శాస్త్రవేత్త',
  'Complete Registration': 'నమోదు పూర్తి చేయండి',
  'Secured with JWT Authentication': 'JWT ధృవీకరణతో సురక్షితం',
  'Compatible with Java Spring Security': 'Java Spring Securityకు అనుకూలం',
  'Failed to sign in. Please check credentials.': 'సైన్ ఇన్ కాలేదు. మీ ఖాతా వివరాలను తనిఖీ చేయండి.',
  'Crop Progression & Comparison': 'పంట పురోగతి మరియు పోలిక',
  'Compare current leaf with past scans or baseline reference': 'ప్రస్తుత ఆకును గత స్కాన్‌లు లేదా ప్రారంభ స్థాయితో పోల్చండి',
  'Compare with past scan:': 'గత స్కాన్‌తో పోల్చండి:',
  'Active Analysis': 'ప్రస్తుత విశ్లేషణ',
  Today: 'ఈ రోజు',
  'Current Scan': 'ప్రస్తుత స్కాన్',
  'Comparative Log': 'పోలిక రికార్డు',
  'No past scans recorded yet. Once you save multiple scans, you can monitor lesion recovery side-by-side here.': 'గత స్కాన్‌లు ఇంకా లేవు. అనేక స్కాన్‌లను భద్రపరిచిన తర్వాత వాటి మార్పులను ఇక్కడ పోల్చవచ్చు.',
  'Please upload a valid image file (JPEG, PNG, WEBP).': 'చెల్లుబాటు అయ్యే చిత్ర ఫైల్‌ను అప్‌లోడ్ చేయండి (JPEG, PNG, WEBP).',
  'Failed to process uploaded image. Please try another file.': 'చిత్రాన్ని ప్రాసెస్ చేయలేకపోయాం. మరో ఫైల్‌తో ప్రయత్నించండి.',
  'Could not process camera image.': 'కెమెరా చిత్రాన్ని ప్రాసెస్ చేయలేకపోయాం.',
  'Camera access denied. Please grant permission in your browser.': 'కెమెరా అనుమతి నిరాకరించబడింది. బ్రౌజర్‌లో అనుమతి ఇవ్వండి.',
  'Could not connect to camera device. Ensure no other application is using it.': 'కెమెరాకు కనెక్ట్ కాలేకపోయాం. మరో యాప్ కెమెరాను ఉపయోగించడం లేదని నిర్ధారించండి.',
  Fungal: 'శిలీంధ్ర',
  Oomycete: 'ఓమైసీట్',
  Bacterial: 'బ్యాక్టీరియా',
  Nutritional: 'పోషక సంబంధిత',
  'Consulting for': 'సలహా పొందుతున్నారు:',
  'Can I safely eat fruit or vegetables from this plant?': 'ఈ మొక్క పండ్లు లేదా కూరగాయలను తినడం సురక్షితమేనా?',
  'Is this treatment safe around pets and beneficial bees?': 'పెంపుడు జంతువులు మరియు తేనెటీగల దగ్గర ఈ చికిత్స సురక్షితమేనా?',
  'How do I sanitize my pruning shears to stop spread?': 'వ్యాధి వ్యాప్తి ఆపడానికి కత్తిరింపు కత్తెరను ఎలా శుభ్రం చేయాలి?',
  'What companion plants help deter this disease naturally?': 'ఈ వ్యాధిని సహజంగా తగ్గించడానికి ఏ తోడు మొక్కలు ఉపయోగపడతాయి?',
  'How long will it take for healthy new foliage to emerge?': 'కొత్త ఆరోగ్యకరమైన ఆకులు రావడానికి ఎంత సమయం పడుతుంది?',
  'Switch to My Scans': 'నా స్కాన్‌లకు మారండి',
  'View Sample 14-Day Timeline': '14 రోజుల నమూనా కాలక్రమం చూడండి',
  'Record New Scan': 'కొత్త స్కాన్ నమోదు చేయండి',
  'Crop Health Trends & Severity Tracker': 'పంట ఆరోగ్య ధోరణులు మరియు తీవ్రత ట్రాకర్',
  'AI Vision Chronology': 'AI విశ్లేషణ కాలక్రమం',
  'Track longitudinal disease severity over time. Verify whether organic/chemical treatments are arresting lesion spread, restoring foliar canopy, or requiring intervention.': 'కాలక్రమేణా వ్యాధి తీవ్రతను గమనించండి. చికిత్సలు వ్యాప్తిని ఆపుతున్నాయా, ఆకుల ఆరోగ్యాన్ని మెరుగుపరుస్తున్నాయా లేదా మరింత చర్య అవసరమా అని పరిశీలించండి.',
  'Health Trajectory': 'ఆరోగ్య పురోగతి',
  'Crop Health Improving': 'పంట ఆరోగ్యం మెరుగవుతోంది',
  'Crop Health Declining': 'పంట ఆరోగ్యం క్షీణిస్తోంది',
  'Crop Condition Stable': 'పంట పరిస్థితి స్థిరంగా ఉంది',
  'Severity decreased by {percent}% since first baseline scan': 'మొదటి స్కాన్‌తో పోలిస్తే తీవ్రత {percent}% తగ్గింది',
  'Severity increased by {percent}% over monitoring window': 'పర్యవేక్షణ సమయంలో తీవ్రత {percent}% పెరిగింది',
  'Pathogen expansion arrested; symptoms are holding steady': 'వ్యాధి వ్యాప్తి ఆగింది; లక్షణాలు స్థిరంగా ఉన్నాయి',
  'Applied treatments are successfully suppressing pathogen sporulation. Continue preventative foliar schedule and monitor new shoots.': 'చికిత్సలు వ్యాధి వ్యాప్తిని తగ్గిస్తున్నాయి. నివారణ పిచికారీ కొనసాగించి కొత్త చిగుళ్లను గమనించండి.',
  'Pathogen pressure is intensifying. Consider escalating treatment dosage, pruning heavily infected foliage, and isolating affected rows immediately.': 'వ్యాధి తీవ్రత పెరుగుతోంది. చికిత్స మోతాదు పెంచడం, తీవ్రంగా దెబ్బతిన్న ఆకులను కత్తిరించడం మరియు ప్రభావిత వరుసలను వేరు చేయడం పరిశీలించండి.',
  'Disease progression is contained. Maintain recommended cultural practices and prepare for next protective spray cycle.': 'వ్యాధి పురోగతి నియంత్రణలో ఉంది. సూచించిన సాగు పద్ధతులను కొనసాగించి తదుపరి రక్షణ పిచికారీకి సిద్ధం అవ్వండి.',
  'Scan more crops to establish a longitudinal baseline.': 'కాలక్రమ విశ్లేషణ కోసం మరిన్ని పంటలను స్కాన్ చేయండి.',
  'No data': 'డేటా లేదు',
  'Updated across {count} scans': '{count} స్కాన్‌లలో నవీకరించబడింది',
  'Latest Damage Area': 'తాజా నష్టం విస్తీర్ణం',
  'affected leaf tissue': 'ప్రభావిత ఆకు భాగం',
  Baseline: 'ప్రారంభ స్థాయి',
  'Active Pathogen': 'క్రియాశీల వ్యాధికారకం',
  'None detected': 'ఏదీ గుర్తించలేదు',
  Plant: 'మొక్క',
  Crop: 'పంట',
  Status: 'స్థితి',
  'Treatment Advisory': 'చికిత్స సూచన',
  'Ask Agronomist': 'వ్యవసాయ నిపుణుడిని అడగండి',
  'Disease Severity Trajectory Curve': 'వ్యాధి తీవ్రత కాలక్రమ రేఖాచిత్రం',
  'Severity % (Lower is better)': 'తీవ్రత % (తక్కువైతే మంచిది)',
  'Health Index (Higher is better)': 'ఆరోగ్య సూచీ (ఎక్కువైతే మంచిది)',
  'All Crops': 'అన్ని పంటలు',
  Critical: 'అత్యంత తీవ్రం',
  Moderate: 'మధ్యస్థం',
  'Healthy / Mild': 'ఆరోగ్యకరం / తక్కువ తీవ్రత',
  damage: 'నష్టం',
  'Healthy / Remission (0-20%)': 'ఆరోగ్యకరం / కోలుకుంటోంది (0-20%)',
  'Moderate Stress (21-50%)': 'మధ్యస్థ ప్రభావం (21-50%)',
  'Severe / Critical (>50%)': 'తీవ్రం / అత్యంత తీవ్రం (>50%)',
  'Click any data node on the line chart to inspect full pathology report.': 'పూర్తి వ్యాధి నివేదికను చూడటానికి రేఖాచిత్రంలోని ఏ బిందువునైనా ఎంచుకోండి.',
  'Inspection Log & Treatment Milestones': 'పరిశీలన రికార్డు మరియు చికిత్స దశలు',
  'recorded checkpoints': 'నమోదైన తనిఖీలు',
  'Leaf scan': 'ఆకు స్కాన్',
  'Inspect Diagnostic Details': 'నిర్ధారణ వివరాలు చూడండి',
  Checkpoint: 'తనిఖీ దశ',
  Pathogen: 'వ్యాధికారకం',
  'leaf area': 'ఆకు విస్తీర్ణం',
  'Field Observation:': 'పొలంలో గమనించినది:',
  'Prescribed Action:': 'సూచించిన చర్య:',
  Close: 'మూసివేయండి',
  'Load in Pathology Dashboard': 'వ్యాధి విశ్లేషణ డ్యాష్‌బోర్డ్‌లో తెరవండి',
  'Failed to sign in. Please check your credentials.': 'సైన్ ఇన్ కాలేదు. మీ ఖాతా వివరాలను తనిఖీ చేయండి.',
  'Failed to create account.': 'ఖాతా సృష్టించలేకపోయాం.',
  farmer: 'రైతు',
  agronomist: 'వ్యవసాయ నిపుణుడు',
  researcher: 'పరిశోధకుడు',
  student: 'విద్యార్థి',
  'Botanical Pathology & Crop Doctor': 'మొక్కల వ్యాధి శాస్త్రం & పంట వైద్యుడు',
  'Precision Crop Health & Disease Intelligence': 'ఖచ్చితమైన పంట ఆరోగ్యం మరియు వ్యాధి విశ్లేషణ',
  'Empowering farmers, agronomists, and researchers with real-time AI vision pathology, longitudinal health trend tracking, and dual organic & chemical spray prescriptions.': 'రైతులు, వ్యవసాయ నిపుణులు మరియు పరిశోధకులకు AI వ్యాధి విశ్లేషణ, ఆరోగ్య ధోరణుల పర్యవేక్షణ, సేంద్రియ మరియు రసాయన చికిత్స సూచనలు అందిస్తుంది.',
  'Longitudinal Health Trends': 'పంట ఆరోగ్య ధోరణులు',
  'Line-chart tracking of crop recovery vs disease progression over time': 'కాలక్రమంలో పంట కోలుకోవడం మరియు వ్యాధి పురోగతిని రేఖాచిత్రంలో చూడండి',
  '50+ Pathogen Profiles': '50కు పైగా వ్యాధికారక వివరాలు',
  'Instant fungal, bacterial, viral, and nutritional lesion classification': 'శిలీంధ్ర, బ్యాక్టీరియా, వైరస్ మరియు పోషక లోపాలను వెంటనే వర్గీకరిస్తుంది',
  'Dual Treatment Prescriptions': 'రెండు రకాల చికిత్స సూచనలు',
  'Organic remedies and exact chemical dosage tank calculations': 'సేంద్రియ చికిత్సలు మరియు రసాయన మోతాదు లెక్కింపు',
  'Multi-Device Sync • Secure Session Storage': 'పరికరాల మధ్య సమకాలీకరణ • సురక్షిత సెషన్ నిల్వ',
  'Back to Crop Doctor & Scanner': 'పంట వైద్యుడు మరియు స్కానర్‌కు తిరిగి వెళ్లండి',
  'Sign In': 'సైన్ ఇన్',
  'Create Account': 'ఖాతా సృష్టించండి',
  'Welcome Back, Grower': 'మళ్లీ స్వాగతం',
  'Create Your FloraScan Account': 'మీ FloraScan ఖాతాను సృష్టించండి',
  'Sign in to access your crop scan history, trends, and dosage records': 'మీ పంట స్కాన్ చరిత్ర, ధోరణులు మరియు మోతాదు రికార్డులను చూడటానికి సైన్ ఇన్ చేయండి',
  'Join the global network of modern farmers and agricultural scientists': 'ఆధునిక రైతులు మరియు వ్యవసాయ శాస్త్రవేత్తల నెట్‌వర్క్‌లో చేరండి',
  'Email Address': 'ఇమెయిల్ చిరునామా',
  Password: 'పాస్‌వర్డ్',
  'Use Demo Password': 'డెమో పాస్‌వర్డ్ ఉపయోగించండి',
  'Sign In to FloraScan': 'FloraScan‌లో సైన్ ఇన్ చేయండి',
  'Instant One-Click Demo Credentials:': 'ఒక క్లిక్ డెమో ఖాతాలు:',
  'Farmer Demo': 'రైతు డెమో',
  'Agronomist Demo': 'వ్యవసాయ నిపుణుల డెమో',
  'Full Name': 'పూర్తి పేరు',
  'Password (min. 6 characters)': 'పాస్‌వర్డ్ (కనీసం 6 అక్షరాలు)',
  'Farm / Enterprise / Institution Name': 'వ్యవసాయ క్షేత్రం / సంస్థ పేరు',
  'Select Role': 'పాత్రను ఎంచుకోండి',
  'Farmer / Grower': 'రైతు / సాగుదారు',
  'Agronomist / Expert': 'వ్యవసాయ నిపుణుడు',
  Researcher: 'పరిశోధకుడు',
  'Student / Scholar': 'విద్యార్థి / పరిశోధక విద్యార్థి',
  'Create Free Account': 'ఉచిత ఖాతా సృష్టించండి',
  'Account created successfully! Welcome to FloraScan.': 'ఖాతా విజయవంతంగా సృష్టించబడింది! FloraScan‌కు స్వాగతం.',
  'My Saved Leaf Scans': 'నా భద్రపరిచిన ఆకు స్కాన్‌లు',
  'Log Out': 'సైన్ అవుట్',
  Register: 'నమోదు',
  'Live Plant Scanner': 'ప్రత్యక్ష మొక్కల స్కానర్',
  'Camera Unavailable': 'కెమెరా అందుబాటులో లేదు',
  'Retry Camera Access': 'కెమెరా యాక్సెస్ మళ్లీ ప్రయత్నించండి',
  'Snapshot Captured': 'ఫోటో తీసుకున్నారు',
  'Align leaf within guide': 'సూచికలో ఆకును సరిచేయండి',
  'Keep camera steady with good natural lighting': 'మంచి సహజ వెలుతురులో కెమెరాను స్థిరంగా ఉంచండి',
  'Switch Camera (Front/Rear)': 'కెమెరా మార్చండి (ముందు/వెనుక)',
  'Retake Photo': 'మళ్లీ ఫోటో తీయండి',
  'Analyze This Leaf': 'ఈ ఆకును విశ్లేషించండి',
  Cancel: 'రద్దు చేయండి',
  'Capture Leaf Scan': 'ఆకు స్కాన్ తీయండి',
  'Non-Plant Subject Detected': 'మొక్క కాని వస్తువు గుర్తించబడింది',
  'Our botanical vision system could not detect distinct plant leaves, stems, flowers, or fruit in this photo. Please upload a clear, focused close-up of foliage or crop leaves under good lighting.': 'ఈ చిత్రంలో ఆకులు, కాండాలు, పూలు లేదా పండ్లను స్పష్టంగా గుర్తించలేకపోయాం. మంచి వెలుతురులో తీసిన ఆకుల దగ్గరి చిత్రాన్ని అప్‌లోడ్ చేయండి.',
  'Tips for best diagnostic accuracy:': 'ఖచ్చితమైన నిర్ధారణ కోసం సూచనలు:',
  'Ensure the leaf is in focus and fills at least 50% of the camera frame': 'ఆకు స్పష్టంగా ఉండి, కెమెరా ఫ్రేమ్‌లో కనీసం సగం భాగాన్ని నింపాలి',
  'Capture both the upper and lower leaf surface if powdery mildew is suspected': 'బూజు తెగులు అనుమానం ఉంటే ఆకు పైభాగం మరియు అడుగుభాగం రెండింటినీ చిత్రీకరించండి',
  'Avoid heavy shadows or extreme overexposure': 'తీవ్రమైన నీడలు లేదా అధిక వెలుతురును నివారించండి',
  'Diagnostic Verdict': 'నిర్ధారణ ఫలితం',
  Severity: 'తీవ్రత',
  Share: 'పంచుకోండి',
  'Copied!': 'కాపీ అయింది!',
  'Copy Diagnosis Summary': 'నిర్ధారణ సారాంశాన్ని కాపీ చేయండి',
  'Print Clinical Plant Report': 'మొక్క నివేదికను ముద్రించండి',
  'Export PDF': 'PDF ఎగుమతి',
  'Consult Dr. Flora': 'డా. ఫ్లోరాను సంప్రదించండి',
  'Host Plant Profile': 'ఆతిథ్య మొక్క వివరాలు',
  Family: 'కుటుంబం',
  'Common Crop': 'సాధారణ పంట పేరు',
  'Botanical Taxon': 'వృక్షశాస్త్ర నామం',
  'Causative Pathogen': 'కారణమైన వ్యాధికారకం',
  'Pathology Quant Analysis': 'వ్యాధి పరిమాణ విశ్లేషణ',
  'Diagnostic Confidence': 'నిర్ధారణ నమ్మక స్థాయి',
  'Foliage Surface Damage': 'ఆకు ఉపరితల నష్టం',
  'Contagion to Neighbor Crops': 'పక్క పంటలకు వ్యాప్తి ప్రమాదం',
  'Saved in Crop Journal': 'పంట చరిత్రలో భద్రపరిచారు',
  'Log to Field History': 'పొలం చరిత్రలో నమోదు చేయండి',
  'Keep track of treatment recovery timeline': 'చికిత్స మరియు కోలుకునే పురోగతిని గమనించండి',
  'Needs Action': 'చర్య అవసరం',
  Treated: 'చికిత్స పూర్తయింది',
  Monitoring: 'పర్యవేక్షణలో ఉంది',
  Resolved: 'పరిష్కరించబడింది',
  Update: 'నవీకరించండి',
  Save: 'భద్రపరచండి',
  'Emergency Triage Protocol (Next 24-48 Hours)': 'అత్యవసర చర్యలు (తదుపరి 24-48 గంటలు)',
  'Pathological Symptoms & Progression': 'వ్యాధి లక్షణాలు మరియు పురోగతి',
  Stage: 'దశ',
  'Key Visual Indicators Observed:': 'గమనించిన ముఖ్య లక్షణాలు:',
  'Impacted Tissues:': 'ప్రభావిత భాగాలు:',
  'Prescription & Treatment Center': 'చికిత్స కేంద్రం',
  'Evidence-based integrated pest and pathogen management': 'ఆధారాలతో కూడిన సమగ్ర చీడపీడలు మరియు వ్యాధి నిర్వహణ',
  'Organic & Biological': 'సేంద్రియ మరియు జీవ నియంత్రణ',
  'Chemical Protectants': 'రసాయన రక్షణ మందులు',
  'Cultural Practices': 'సాగు పద్ధతులు',
  'No specific organic treatments required.': 'ప్రత్యేక సేంద్రియ చికిత్స అవసరం లేదు.',
  'Calculate Dilution': 'మిశ్రమ మోతాదు లెక్కించండి',
  'Preparation & Spray:': 'తయారీ మరియు పిచికారీ:',
  'Frequency:': 'వాడుక వ్యవధి:',
  'No chemical treatments necessary for this case.': 'ఈ సందర్భానికి రసాయన చికిత్స అవసరం లేదు.',
  'Calculate Dosage': 'మోతాదు లెక్కించండి',
  'Active:': 'క్రియాశీల పదార్థం:',
  'Trade names:': 'వాణిజ్య పేర్లు:',
  'Safety / Pre-harvest Interval:': 'భద్రత / కోతకు ముందు విరామం:',
  'Proactive Prevention': 'ముందస్తు నివారణ',
  'Recovery Prognosis': 'కోలుకునే అంచనా',
  'Crop Health Journal': 'పంట ఆరోగ్య చరిత్ర',
  'logged scans & pathology records': 'స్కాన్‌లు మరియు వ్యాధి రికార్డులు',
  All: 'అన్నీ',
  'No scans found': 'స్కాన్‌లు ఏవీ లేవు',
  'Capture or analyze leaf photos and click "Save to Field History" to track progress over time.': 'ఆకుల ఫోటోలను విశ్లేషించి, పురోగతిని చూడటానికి "పొలం చరిత్రలో నమోదు చేయండి" ఎంచుకోండి.',
  'severity': 'తీవ్రత',
  'View Analysis': 'విశ్లేషణ చూడండి',
  'Delete Record': 'రికార్డును తొలగించండి',
  'Clear All History': 'చరిత్ర మొత్తాన్ని తొలగించండి',
  'records saved': 'రికార్డులు భద్రపరిచారు',
  'Dosage & Tank Mix Calculator': 'మోతాదు మరియు ట్యాంక్ మిశ్రమ లెక్కింపు',
  'sq meters': 'చ.మీటర్లు',
  'sq feet': 'చ.అడుగులు',
  'Calibrated dilution & spray volumes for crop treatments': 'పంట చికిత్సల కోసం సరైన మిశ్రమం మరియు పిచికారీ పరిమాణం',
  'Treatment Substance or Active Chemical': 'చికిత్స పదార్థం లేదా క్రియాశీల రసాయనం',
  'Garden / Plot Size': 'తోట / పొలం పరిమాణం',
  Plants: 'మొక్కలు',
  'Severity Level': 'తీవ్రత స్థాయి',
  'Mild (Preventive / Early)': 'తక్కువ (నివారణ / ప్రారంభ దశ)',
  'Moderate (Active spots)': 'మధ్యస్థం (మచ్చలు కనిపిస్తున్నాయి)',
  'Severe (Heavy infection)': 'తీవ్రం (వ్యాధి ఎక్కువగా ఉంది)',
  'Critical (Emergency knockdown)': 'అత్యంత తీవ్రం (అత్యవసర చర్య)',
  'Calculating Precise Volume...': 'ఖచ్చితమైన పరిమాణాన్ని లెక్కిస్తోంది...',
  'Calculate Mix Recipe': 'మిశ్రమ మోతాదు లెక్కించండి',
  'Calibrated Application Formula': 'సరైన వినియోగ మోతాదు',
  Target: 'లక్ష్యం',
  'Total Water Required': 'అవసరమైన మొత్తం నీరు',
  'Substance Quantity': 'పదార్థ పరిమాణం',
  'Concentration Ratio:': 'గాఢత నిష్పత్తి:',
  'Spray Technique:': 'పిచికారీ విధానం:',
  'Best Spray Window:': 'పిచికారీకి అనువైన సమయం:',
  'Safety & Pollinator Precautions:': 'భద్రత మరియు పరాగసంపర్క కీటకాల జాగ్రత్తలు:',
  'Botanical Pathology Atlas': 'మొక్కల వ్యాధుల సూచిక',
  'Comprehensive reference encyclopedia of crop diseases & pathogens': 'పంట వ్యాధులు మరియు వ్యాధికారకాల సమగ్ర సూచిక',
  'Search diseases, pathogens, crops (e.g. Tomato, Mildew, Phytophthora)...': 'వ్యాధులు, వ్యాధికారకాలు లేదా పంటల కోసం వెతకండి...',
  'No diseases match your search criteria': 'మీ శోధనకు సరిపోయే వ్యాధులు లేవు',
  'Try searching for broader keywords like "Blight", "Tomato", or "Grape".': 'వ్యాధి పేరు లేదా పంట పేరుతో మళ్లీ వెతకండి.',
  Hosts: 'ఆతిథ్య పంటలు:',
  Collapse: 'మూసివేయండి',
  Details: 'వివరాలు',
  'Favorable Environmental Conditions:': 'అనుకూల వాతావరణ పరిస్థితులు:',
  'Visual Clinical Symptoms:': 'కనిపించే వ్యాధి లక్షణాలు:',
  'Organic & Biological Controls': 'సేంద్రియ మరియు జీవ నియంత్రణ',
  'Target Chemical Protectants': 'లక్ష్యిత రసాయన రక్షణ మందులు',
  'Preventive Agronomy Tips:': 'నివారణ సాగు సూచనలు:',
  'Master Agronomist': 'వ్యవసాయ నిపుణుడు',
  'Agricultural pathology guidance': 'వ్యవసాయ వ్యాధులపై మార్గదర్శకం',
  'Dr. Flora is formulating agronomy advice...': 'డా. ఫ్లోరా వ్యవసాయ సలహాను సిద్ధం చేస్తున్నారు...',
  'Quick Questions:': 'త్వరిత ప్రశ్నలు:',
  'Ask Dr. Flora about treatment, soil, safety...': 'చికిత్స, నేల లేదా భద్రత గురించి అడగండి...',
  'Botanical Pathology & AI Crop Doctor': 'మొక్కల వ్యాధి శాస్త్రం & AI పంట వైద్యుడు',
  'Health Trends': 'పంట ఆరోగ్య ధోరణులు',
  'Track crop disease severity trajectory & recovery over time': 'కాలక్రమేణా పంట వ్యాధి తీవ్రత మరియు కోలుకోవడాన్ని చూడండి',
  'Disease Atlas': 'వ్యాధుల సూచిక',
  'Dosage Calc': 'మోతాదు లెక్కింపు',
  'Crop Log': 'పంట రికార్డు',
  'Ask Dr. Flora': 'డా. ఫ్లోరాను అడగండి',
  Dismiss: 'తొలగించు',
  'Are you sure you want to clear your entire crop scan history?': 'మీ పంట స్కాన్ చరిత్ర మొత్తాన్ని తొలగించాలనుకుంటున్నారా?',
  'Scan Another Plant or Leaf': 'మరో మొక్క లేదా ఆకును స్కాన్ చేయండి',
  'Compare with Past Scan': 'మునుపటి స్కాన్‌తో పోల్చండి',
  'Analyzing Foliar Pathology': 'ఆకు వ్యాధిని విశ్లేషిస్తోంది',
  'Calibrating botanical vision sensors...': 'మొక్కల విశ్లేషణ సెన్సార్లను సిద్ధం చేస్తోంది...',
  'Screening for fungal, bacterial & viral pathogens...': 'శిలీంధ్ర, బ్యాక్టీరియా మరియు వైరస్ వ్యాధికారకాలను పరిశీలిస్తోంది...',
  'Mapping lesion coordinates & calculating leaf damage %...': 'ఆకు మచ్చలను గుర్తించి నష్టం శాతాన్ని లెక్కిస్తోంది...',
  'Synthesizing dual organic & chemical prescriptions...': 'సేంద్రియ మరియు రసాయన చికిత్సలను సిద్ధం చేస్తోంది...',
  'AI Vision Disease Detection & Integrated Pest Management': 'AI ద్వారా వ్యాధి గుర్తింపు మరియు సమగ్ర చీడపీడల నిర్వహణ',
  'Identify Plant Diseases in Seconds.': 'మొక్కల వ్యాధులను క్షణాల్లో గుర్తించండి.',
  'Protect Your Harvest.': 'మీ పంటను కాపాడండి.',
  'Snap or upload a photo of infected leaves, stems, or crops. Get instant scientific pathogen identification, lesion severity assessment, dual organic/chemical treatment plans, and continuous health tracking.': 'వ్యాధిగ్రస్త ఆకులు, కాండాలు లేదా పంటల ఫోటో తీయండి లేదా అప్‌లోడ్ చేయండి. వ్యాధికారక గుర్తింపు, నష్టం అంచనా, సేంద్రియ/రసాయన చికిత్స సూచనలు మరియు ఆరోగ్య పర్యవేక్షణ పొందండి.',
  'Upload Leaf Photo': 'ఆకు ఫోటో అప్‌లోడ్ చేయండి',
  'Open Live Camera': 'కెమెరా తెరవండి',
  'or drag & drop leaf images here (JPEG, PNG, WEBP up to 30MB)': 'లేదా ఆకు చిత్రాలను ఇక్కడికి లాగండి (JPEG, PNG, WEBP, గరిష్ఠం 30MB)',
  'Plant Species (Optional)': 'మొక్క జాతి (ఐచ్ఛికం)',
  'e.g. Tomato, Corn, Grape, Rose': 'ఉదా. టమాటా, మొక్కజొన్న, ద్రాక్ష, గులాబీ',
  'Growing Environment (Optional)': 'పెరుగుదల వాతావరణం (ఐచ్ఛికం)',
  'e.g. Greenhouse, Outdoor field, Raised bed': 'ఉదా. గ్రీన్‌హౌస్, బహిరంగ పొలం, ఎత్తైన మడి',
  'Try With Reference Specimen Samples': 'నమూనా ఆకులతో ప్రయత్నించండి',
  'Click any curated leaf sample below to run immediate diagnostic analysis': 'తక్షణ విశ్లేషణ కోసం దిగువ నమూనా ఆకుపై క్లిక్ చేయండి',
  'Scan Now': 'ఇప్పుడే స్కాన్ చేయండి',
  'Visual Pathogen Screening': 'వ్యాధికారకాల దృశ్య పరిశీలన',
  'Identifies 50+ fungal, oomycete, bacterial, viral, and nutrient deficiencies with visual bounding box lesion localization.': 'శిలీంధ్ర, బ్యాక్టీరియా, వైరస్ మరియు పోషక లోపాలతో సహా 50కు పైగా సమస్యలను గుర్తించి, ఆకు నష్టం స్థానాన్ని చూపిస్తుంది.',
  'Dual-Track Action Plans': 'రెండు రకాల చికిత్స ప్రణాళికలు',
  'Provides both bio-organic solutions (neem, bacillus, compost teas) and active chemical protectants with safety intervals.': 'వేప, బాసిల్లస్, కంపోస్ట్ ద్రావణాలు వంటి జీవ సేంద్రియ పరిష్కారాలతో పాటు రసాయన చికిత్సలు మరియు భద్రతా విరామాలను సూచిస్తుంది.',
  'Calibrated Dosage & Doctor Chat': 'సరైన మోతాదు మరియు నిపుణుల సలహా',
  'Calculate tank mix volumes tailored to your plot size and consult Dr. Flora for specialized agronomic advice.': 'మీ పొలం పరిమాణానికి తగిన స్ప్రే మిశ్రమ మోతాదును లెక్కించి, డా. ఫ్లోరా నుంచి వ్యవసాయ సలహా పొందండి.',
  'Pathology Encyclopedia': 'మొక్కల వ్యాధుల విజ్ఞానసర్వస్వం',
  'Spray Dilution Tool': 'స్ప్రే మిశ్రమ లెక్కింపు',
  'Agronomist Consultation': 'వ్యవసాయ నిపుణుల సలహా',
  'FloraScan AI Botanical Pathology System. Powered by Gemini 3.8 Flash.': 'మొక్కల వ్యాధి విశ్లేషణ వ్యవస్థ. Gemini 3.8 Flash ద్వారా.',
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    try {
      return localStorage.getItem('florascan_language') === 'te' ? 'te' : 'en';
    } catch {
      return 'en';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('florascan_language', language);
    } catch {}
  }, [language]);

  const t = (text: string) => (language === 'te' ? teluguTranslations[text] ?? text : text);

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};